# Generated by Django 4.2.11 on 2024-03-12 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantityingredient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='quantityingredient',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
        migrations.DeleteModel(
            name='QuantityIngredient',
        ),
    ]
