# Generated by Django 4.2.11 on 2024-03-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_ingredient_quantity_shoppingcart_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_shopping_cart',
        ),
    ]
