# Generated by Django 4.2.11 on 2024-03-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_amountingredient_ingredient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AmountIngredient',
        ),
    ]
