# Generated by Django 4.2.11 on 2024-03-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_delete_amountingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
