# Generated by Django 4.2.11 on 2024-03-13 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipeingredient_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredient', to='recipes.ingredient'),
            preserve_default=False,
        ),
    ]
