# Generated by Django 4.2.11 on 2024-03-16 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_remove_favorites_unique_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorited',
        ),
    ]
