# Generated by Django 4.2.11 on 2024-03-26 22:18

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_follow_unique_follow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[core.validators.validate_username], verbose_name='Имя пользователя'),
        ),
    ]
